apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic-stack
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30000
      name: rest
    - protocol: TCP
      port: 9300
      targetPort: 9300
      nodePort: 30001
      name: inter-node